// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_CHECK_MOBAGO_FLATBUFFER_H_
#define FLATBUFFERS_GENERATED_CHECK_MOBAGO_FLATBUFFER_H_

#include "flatbuffers/flatbuffers.h"


namespace MobaGo {
namespace FlatBuffer {

struct MsgClientValidation;

struct MsgClientValidation FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  uint32_t frame_no() const { return GetField<uint32_t>(4, 0); }
  const flatbuffers::String *check_value() const { return GetPointer<const flatbuffers::String *>(6); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, 4 /* frame_no */) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 6 /* check_value */) &&
           verifier.Verify(check_value()) &&
           verifier.EndTable();
  }
};

struct MsgClientValidationBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_frame_no(uint32_t frame_no) { fbb_.AddElement<uint32_t>(4, frame_no, 0); }
  void add_check_value(flatbuffers::Offset<flatbuffers::String> check_value) { fbb_.AddOffset(6, check_value); }
  MsgClientValidationBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  MsgClientValidationBuilder &operator=(const MsgClientValidationBuilder &);
  flatbuffers::Offset<MsgClientValidation> Finish() {
    auto o = flatbuffers::Offset<MsgClientValidation>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<MsgClientValidation> CreateMsgClientValidation(flatbuffers::FlatBufferBuilder &_fbb,
   uint32_t frame_no = 0,
   flatbuffers::Offset<flatbuffers::String> check_value = 0) {
  MsgClientValidationBuilder builder_(_fbb);
  builder_.add_check_value(check_value);
  builder_.add_frame_no(frame_no);
  return builder_.Finish();
}

}  // namespace FlatBuffer
}  // namespace MobaGo

#endif  // FLATBUFFERS_GENERATED_CHECK_MOBAGO_FLATBUFFER_H_
