// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_COMMON_MOBAGO_FLATBUFFER_H_
#define FLATBUFFERS_GENERATED_COMMON_MOBAGO_FLATBUFFER_H_

#include "flatbuffers/flatbuffers.h"


namespace MobaGo {
namespace FlatBuffer {

struct MsgBody;
struct IntVec3;

MANUALLY_ALIGNED_STRUCT(4) IntVec3 FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t x_;
  int32_t y_;
  int32_t z_;

 public:
  IntVec3(int32_t x, int32_t y, int32_t z)
    : x_(flatbuffers::EndianScalar(x)), y_(flatbuffers::EndianScalar(y)), z_(flatbuffers::EndianScalar(z)) { }

  int32_t x() const { return flatbuffers::EndianScalar(x_); }
  int32_t y() const { return flatbuffers::EndianScalar(y_); }
  int32_t z() const { return flatbuffers::EndianScalar(z_); }
};
STRUCT_END(IntVec3, 12);

struct MsgBody FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const flatbuffers::Vector<uint8_t> *data() const { return GetPointer<const flatbuffers::Vector<uint8_t> *>(4); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* data */) &&
           verifier.Verify(data()) &&
           verifier.EndTable();
  }
};

struct MsgBodyBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_data(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data) { fbb_.AddOffset(4, data); }
  MsgBodyBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  MsgBodyBuilder &operator=(const MsgBodyBuilder &);
  flatbuffers::Offset<MsgBody> Finish() {
    auto o = flatbuffers::Offset<MsgBody>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<MsgBody> CreateMsgBody(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data = 0) {
  MsgBodyBuilder builder_(_fbb);
  builder_.add_data(data);
  return builder_.Finish();
}

}  // namespace FlatBuffer
}  // namespace MobaGo

#endif  // FLATBUFFERS_GENERATED_COMMON_MOBAGO_FLATBUFFER_H_
