// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GUID_MOBAGO_FLATBUFFER_H_
#define FLATBUFFERS_GENERATED_GUID_MOBAGO_FLATBUFFER_H_

#include "flatbuffers/flatbuffers.h"


namespace MobaGo {
namespace FlatBuffer {

struct SMsgRequestGuidReq;
struct SMsgRequestGuidAck;

struct SMsgRequestGuidReq FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  uint32_t request_number() const { return GetField<uint32_t>(4, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, 4 /* request_number */) &&
           verifier.EndTable();
  }
};

struct SMsgRequestGuidReqBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_request_number(uint32_t request_number) { fbb_.AddElement<uint32_t>(4, request_number, 0); }
  SMsgRequestGuidReqBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  SMsgRequestGuidReqBuilder &operator=(const SMsgRequestGuidReqBuilder &);
  flatbuffers::Offset<SMsgRequestGuidReq> Finish() {
    auto o = flatbuffers::Offset<SMsgRequestGuidReq>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<SMsgRequestGuidReq> CreateSMsgRequestGuidReq(flatbuffers::FlatBufferBuilder &_fbb,
   uint32_t request_number = 0) {
  SMsgRequestGuidReqBuilder builder_(_fbb);
  builder_.add_request_number(request_number);
  return builder_.Finish();
}

struct SMsgRequestGuidAck FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  uint32_t seed_index() const { return GetField<uint32_t>(4, 0); }
  uint64_t start_index() const { return GetField<uint64_t>(6, 0); }
  uint32_t create_number() const { return GetField<uint32_t>(8, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, 4 /* seed_index */) &&
           VerifyField<uint64_t>(verifier, 6 /* start_index */) &&
           VerifyField<uint32_t>(verifier, 8 /* create_number */) &&
           verifier.EndTable();
  }
};

struct SMsgRequestGuidAckBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_seed_index(uint32_t seed_index) { fbb_.AddElement<uint32_t>(4, seed_index, 0); }
  void add_start_index(uint64_t start_index) { fbb_.AddElement<uint64_t>(6, start_index, 0); }
  void add_create_number(uint32_t create_number) { fbb_.AddElement<uint32_t>(8, create_number, 0); }
  SMsgRequestGuidAckBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  SMsgRequestGuidAckBuilder &operator=(const SMsgRequestGuidAckBuilder &);
  flatbuffers::Offset<SMsgRequestGuidAck> Finish() {
    auto o = flatbuffers::Offset<SMsgRequestGuidAck>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<SMsgRequestGuidAck> CreateSMsgRequestGuidAck(flatbuffers::FlatBufferBuilder &_fbb,
   uint32_t seed_index = 0,
   uint64_t start_index = 0,
   uint32_t create_number = 0) {
  SMsgRequestGuidAckBuilder builder_(_fbb);
  builder_.add_start_index(start_index);
  builder_.add_create_number(create_number);
  builder_.add_seed_index(seed_index);
  return builder_.Finish();
}

}  // namespace FlatBuffer
}  // namespace MobaGo

#endif  // FLATBUFFERS_GENERATED_GUID_MOBAGO_FLATBUFFER_H_
